# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

sum <- function(a, b) {
    .Call(`_calc_sum`, a, b)
}

mul <- function(a, b) {
    .Call(`_calc_mul`, a, b)
}

diff <- function(a, b) {
    .Call(`_calc_diff`, a, b)
}

div <- function(a, b) {
    .Call(`_calc_div`, a, b)
}

rcpparma_hello_world <- function() {
    .Call(`_calc_rcpparma_hello_world`)
}

rcpparma_outerproduct <- function(x) {
    .Call(`_calc_rcpparma_outerproduct`, x)
}

rcpparma_innerproduct <- function(x) {
    .Call(`_calc_rcpparma_innerproduct`, x)
}

rcpparma_bothproducts <- function(x) {
    .Call(`_calc_rcpparma_bothproducts`, x)
}

